version: '3.7'
services:
  backend:
    tty: true
    container_name: milhas-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8000:8000
    volumes:
      - api-data:/app

volumes:
 api-data:
   driver: local
   driver_opts:
     o: bind
     type: none
     device: ./milhas
