version: '3.7'
services:
  backend:
    container_name: milhas-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8000:8000
    volumes:
      - ~/Apps/milhas:/app
    